package com.brookr.FloatyShop.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@DynamoDBTable(tableName = "Customers")
public class Customer {

    private String id;
    private String name;
    private int orders;
    private String pic;
    private boolean vip;
    private List<Map<String, String>> history;
    private Map<String,String> company;


    public Customer() {

    }

    public Customer(String pic, int orders) {
        this.pic = pic;
        this.orders = orders;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public int getOrders() {
        return orders;
    }

    public void setId(String id) {
        this.id = id;
    }


    public void setOrders(int orders) {
        this.orders = orders;
    }

    @DynamoDBAttribute
    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    @DynamoDBAttribute
    public List<Map<String, String>> getHistory() {
        return history;
    }

    public void setHistory(List<Map<String, String>> history) {
        this.history = history;
    }

    @DynamoDBAttribute
    public boolean isVip() {
        return vip;
    }

    public void setVip(boolean vip) {
        this.vip = vip;
    }

    @DynamoDBAttribute
    public Map<String,String> getCompany() {
        return company;
    }

    public void setCompany(Map<String,String> company) {
        this.company = company;
    }


    public boolean toggleVipStatus() {
        this.vip = !this.vip;
        return this.vip;
    }
}